#!/bin/bash
# Define the paths for the source and destination directories
src_dir=$(pwd)
dest_dir=$(dirname $(pwd))
# Copy only the HTML files that are newer or do not exist in the destination directory
rsync -av --ignore-existing --update --include="*.html" --exclude="*" "${src_dir}/" "${dest_dir}/"

